import type { Metadata } from "next";
import { DM_Sans } from 'next/font/google'
import { Navbar } from "./navbar";
import { Footer } from "./footer";

const dmSans = DM_Sans({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col min-h-screen">

            <Navbar />
            <div className=" flex-1 bg-[#F4F4F0]">
                {children}
            </div>
            <Footer />
        </div>
    );
}
